// Generated by https://quicktype.io

export interface IDashboardSummaryResponse {
    numberOfOrders:           number;
    paidOrders:               number;
    unpaidOrders:             number;
    numberOfClients:          number;
    numberOfProducts:         number;
    productsWithNoInventory:  number;
    productsWithLowInventory: number;
}
